### ISSUE TITLE
what niche does this serve?

### ISSUE THREAD

**Issue by karenetheridge** [hoytech/Log-File-Rolling#2]
"This module was forked from the Log::Dispatch::File::Rolling to add the symlink feature and fix a few other minor issues (see the Changes file for details)." -- were you aware of Log::Dispatch::File::Stamped?

**Comment by hoytech** [comment]
Yes, I was aware.

This is the second time you've done a hit-and-run promotion of your module without addressing my main concern: I want to be able to run "tail -F logfile.current" and see all the log messages from an app without worrying about time roll-overs. This module, since it incorporates my ignored patch to Log::Dispatch::File::Rolling (https://rt.cpan.org/Public/Bug/Display.html?id=95900), provides this functionality with a "current symlink" feature.

I'm not sure what "niche" this module serves, but in addition to the current symlink feature, it has the following advantages over Log::Dispatch::File::Stamped:
- It's possible to timestamp files in UTC (and this is the default). Unless you can ensure that all machines are set to UTC, local time always becomes problematic when organisations expand to cover multiple time-zones. It also causes confusion around daylight savings roll-overs.
- Timestamp caching. I used to think Log::Dispatch::File::Stamped did this, but looking again I see that every message executes localtime() and strftime() and the only computation saved is some string concatenation and a catfile() call. In my module if time()==$previous_time, then no further time logic is computed for that message.
- Because it's based off Log::Dispatch::File::Rolling, it's explicitly multi-process and fork()-safe (write(2) is not atomic for all filesystems). I've generated TBs of logs with LDFR on linux, BSD, and solaris and I'm confident in its implementation.
- Doesn't depend on Log::Dispatch (this advantage is obviously subjective).

So exactly what niche does Log::Dispatch::File::Stamped serve?

**Comment by karenetheridge** [comment]
> This is the second time you've done a hit-and-run promotion of your module

Hey, this is no hit-and-run -- I'm still here. And I don't descend into violence.  I couldn't find any record of contacting you before -- was that regarding a different module? Sorry to have bothered you again, since apparently I've struck a nerve.

It's not my module though -- it's Eric Cholet's, one of the authors listed in the lineage of yours.

I've made some notes on the efficiency concerns you've noted re ::File::Stamped. It looks like there's definitely some improvement that can be made here, and being able to use UTC instead of localtime would definitely be useful to many.

**Comment by hoytech** [comment]
It's OK, no need to apologize. You haven't bothered me. We communicated about this issue in the RT ticket I linked above. I was just irritated at the implication that this module must only be suitable for some "niche" purpose, combined with my desire for a symlink being discounted, again.

BTW, I just did a bit of checking and found a couple of modules that _do_ support symlinks except neither of them handle timezones to my requirements:

File::Stamped - Only supports localtime.

File::RotateLogs - Only supports a fixed offset from UTC. I guess this is acceptable for JST (which has no daylight savings time) but I still need EST/EDT for some legacy apps unfortunately.

**Comment by karenetheridge** [comment]
> We communicated about this issue in the RT ticket I linked above

Ah yes, I see now!

Having a symlink to the currently-active file is quite a sane one. I wonder if this could be worked into Log::Dispatch::File itself? Although it might not make total sense there, since in the parent class the filename is expected to always be the same.  So keeping the symlink current in ::Stamped would be reasonable, since that's where the changing-filename logic lives.

I've created some wishlist tickets to track these --  
- https://rt.cpan.org/Ticket/Display.html?id=113274 (symlink)
- https://rt.cpan.org/Ticket/Display.html?id=113275 (cache localtime result)
- https://rt.cpan.org/Ticket/Display.html?id=113276 (globaltime instead of localtime)

**Comment by hoytech** [comment]
Thanks! I updated RT 113275 with some more details.

**Comment by karenetheridge** [comment]
I've resolved RT#113275 (save some syscalls) and RT#113276 (support UTC as well as localtime) in the new release 0.17.

**Comment by hoytech** [comment]
Very cool, thanks for letting me know.
